version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: game_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root_password
    networks:
      - app_network

  mysql:
    image: mysql/mysql-server
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data: